services:
  - type: web
    name: queue-cure-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DEFAULT_CONSULT_MINUTES
        value: "10"
