spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/queuecure
    username: queuecure
    password: queuecure
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    serialization:
      write-dates-as-timestamps: false

clinic:
  default_consult_minutes: 10

server:
  port: 8080

